# Bridge mapping configuration
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/model/husky/cmd_vel"
  ros_type_name: "geometry_msgs/msg/TwistStamped"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/husky/scan/points"
  gz_topic_name: "/world/baylands_terrain/model/husky/link/base_link/sensor/front_laser/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "/clock"
  gz_topic_name: "/world/baylands_terrain/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS