bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    bt_loop_duration: 100
    always_reload_bt_xml: True
    default_navigate_with_operations_bt_xml: "$(find-pkg-share nav2_operations_bringup)/config/bt/predefined_operations.xml"
    navigators: ["navigate_with_operations"]
    navigate_with_operations:
      plugin: nav2_operations_navigator::NavigateWithOperations
    plugin_lib_names:
      - nav2_set_blade_state_bt_node
      - nav2_set_camera_yaw_bt_node

blade_server:
  ros__parameters:
    action_server_result_timeout: 10.0
    blade_command_topic: "/lawnmower/blade_command"

camera_server:
  ros__parameters:
    action_server_result_timeout: 10.0
    max_rotation_speed: 45.0
    tolerance: 0.5
    camera_mount_offset: 0.0

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 50.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: True
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      max_linear_vel: 0.5
      min_linear_vel: -0.5
      max_angular_vel: 2.5
      min_angular_vel: -2.5
      max_linear_accel: 2.5
      max_linear_decel: -2.5
      max_angular_accel: 3.2
      max_angular_decel: -3.2
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 1.8
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.05
      approach_velocity_scaling_dist: 0.6
      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_linear_velocity_scaling: true
      use_fixed_curvature_lookahead: false
      curvature_lookahead_dist: 0.25
      use_cost_regulated_linear_velocity_scaling: false
      cost_scaling_dist: 0.3
      cost_scaling_gain: 1.0
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.25
      use_rotate_to_heading: true
      allow_reversing: false
      rotate_to_heading_min_angle: 0.785
      min_distance_to_obstacle: 0.0
      stateful: true
      use_dynamic_window: false



planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true


local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      transform_tolerance: 0.1
      update_frequency: 10.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_link
      rolling_window: true
      width: 6
      height: 6
      track_unknown_space: false
      resolution: 0.05
      footprint: "[ [1.75, 1.125], [1.75, -1.125], [-1.75, -1.125], [-1.75, 1.125] ]"
      plugins: ["voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 3.00
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: False
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      always_send_full_costmap: True


global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      update_frequency: 5.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      footprint: "[ [1.75, 1.125], [1.75, -1.125], [-1.75, -1.125], [-1.75, 1.125] ]"
      resolution: 0.1
      rolling_window: True
      width: 50
      height: 50
      track_unknown_space: false
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          inf_is_valid: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 3.00
      always_send_full_costmap: True


behavior_server:
  ros__parameters:
    use_sim_time: True
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 100.0
    behavior_plugins:
      [drive_on_heading, backup, wait, spin]
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    backup:
      plugin: "nav2_behaviors::BackUp"
    wait:
      plugin: "nav2_behaviors::Wait"
    spin:
      plugin: "nav2_behaviors::Spin"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.2
    simulate_ahead_time: 0.001
    max_rotational_vel: 10.7
    min_rotational_vel: 10.4
    rotational_acc_lim: 3.2


rviz_goal_client:
  ros__parameters:
    bt_xml_file: "/ros2_ws/src/nav2_operations_bringup/config/bt/predefined_operations.xml"

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: "OPEN_LOOP"
    max_velocity: [0.5, 0.0, 2.5]
    min_velocity: [-0.5, 0.0, -2.5]
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0
    max_accel: [2.5, 0.0, 3.2]
    max_decel: [-2.5, 0.0, -3.2]
    odom_topic: "odom"
    odom_duration: 0.1
    use_realtime_priority: false
    enable_stamped_cmd_vel: false
    stamp_smoothed_velocity_with_smoothing_time: false  # ONLY IN JAZZY
