<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>nav2_semantic_segmentation_demo</name>
  <version>0.0.0</version>
  <description>Metapackage for semantic segmentation demo packages</description>
  <maintainer email="user@example.com">User</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>semantic_segmentation_node</exec_depend>
  <exec_depend>semantic_segmentation_sim</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

